name: Weekly Run

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python Python_code.py
      - name: Commit and Push Output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Auto update output"
          git push
